name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest 

      - name: Run Unit Tests
        run: |
          PYTHONPATH=$(pwd) pytest test/

      - name: Bandit SAST Scan
        run: |
          pip install bandit
          bandit -r .

      - name: Build Docker Image
        run: |
          docker build -t flask_todo_app .

      - name: Start App for DAST
        run: |
          docker run -d -p 5000:5000 --name flaskapp flask_todo_app
          sleep 5

      - name: OWASP ZAP DAST Scan
        uses: zaproxy/action-baseline@v0.10.0 
        with: 
          target: "http://localhost:5000"
          fail_action: false
          cmd_options: >
            -I
            -J report_json.json
            -w report_md.md
            -r report_html.html
            
          
            
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zapreport
          path: |
            report_json.json
            report_md.md
            report_html.html
          

      - name: Deploy to Staging
        run: echo "Simulated deployment step to staging (replace this)."
